[project]
name = "{{PROJECT_NAME}}"
version = "0.1.0"
description = ""
authors = [
    { name = "{{AUTHOR_NAME}}", email = "{{AUTHOR_EMAIL}}" }
]

[dependencies]
libs = []

[build]
language = "{{LANGUAGE}}"
std = "{{STD}}"
entry = "{{ENTRY_POINT}}"
system = "{{BUILD_SYSTEM}}"
sources = ["src"]
output = "build"

[build.flags]
common = ["-Wall", "-Wextra"]
debug = ["-g", "-O0"]
release = ["-O2", "-DNDEBUG"]
